name: 'actions-android-ci'
description: 'Run Android build with GitHub Actions'
author: 'xdtianyu'

branding:
  color: green
  icon: package

runs:
  using: 'docker'
  image: 'Dockerfile'
  volumes: 
    - {{ $github.workplace }}/.opt/cache:/opt/cache
    - {{ $github.workplace }}/.opt/sdk:/opt/sdk
    - {{ $github.workplace }}/.opt/ndk:/opt/ndk
